### ISSUE TITLE
Redmi 6A compatibility

### ISSUE THREAD

**Issue by nstepanets** [TwrpBuilder/android_device_xiaomi_cereus#1]
Is TWRP suitable for Redmi 6A (cactus)? Redmi 6A was noted as having TWRP, but I see TWRP only for Redmi 6 (cereus)

**Comment by bdxoul** [comment]
> 
> 
> Is TWRP suitable for Redmi 6A (cactus)? Redmi 6A was noted as having TWRP, but I see TWRP only for Redmi 6 (cereus)

not workingit's saying disc corrupted
